/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 AutomaticWire.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/AutomaticWire.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Провод_питания001.geometry} material={materials['Material.015']} position={[-14.752, 17.488, 9.428]} scale={[0.686, 1.042, 0.686]} />
    </group>
  )
}

useGLTF.preload('/AutomaticWire.gltf')
