/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Bullet.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Bullet.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['Iron with Splashed Paint']} position={[-1.69, 17.507, 5.664]} scale={0.232} />
    </group>
  )
}

useGLTF.preload('/Bullet.gltf')
