/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Button1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Button1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} position={[-5.75, 17.729, 4.957]} scale={[0.493, 0.072, 0.493]} />
    </group>
  )
}

useGLTF.preload('/Button1.gltf')
