/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Capatitor.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Capatitor.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.446, 18.179, 6.849]} rotation={[-Math.PI, 0, 0.011]} scale={0.512}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['Material.019']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Capatitor.gltf')
