/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Coil.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Coil.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Катушка.geometry} material={materials['Material.010']} position={[0.423, 19.535, 6.652]} scale={[0.044, 0.038, 0.038]} />
    </group>
  )
}

useGLTF.preload('/Coil.gltf')
