/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Contact1Capacitor.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Contact1Capacitor.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.241, 17.662, 6.123]} rotation={[-1.57, 0, Math.PI]} scale={[-0.099, -0.007, -0.099]}>
        <mesh geometry={nodes.Основа_контакта_2004.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Основа_контакта_2004_1.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Contact1Capacitor.gltf')
