/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Contacts.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Contacts.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Основа_контакта_2.geometry} material={materials['Material.007']} position={[0.684, 19.582, 5.723]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.047, -0.003, -0.047]} />
    </group>
  )
}

useGLTF.preload('/Contacts.gltf')
