/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Diod.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Diod.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-10.011, 17.418, 4.883]} scale={[0.084, 0.084, 0.081]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Teak Wood 01']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube006_6.geometry} material={materials['Material.012']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Diod.gltf')
