/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Fon.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Fon.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.028']} position={[-3.598, 32.28, 254.649]} rotation={[Math.PI / 2, 0, 0]} scale={[57.417, 57.417, 79.623]} />
    </group>
  )
}

useGLTF.preload('/Fon.gltf')
