/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LampHolder.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/LampHolder.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.002']} position={[-7.728, 17.402, 4.838]} scale={[0.57, 0.051, 0.57]} />
    </group>
  )
}

useGLTF.preload('/LampHolder.gltf')
