/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pendulum.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pendulum.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[11.155, 27.201, 6.955]} rotation={[Math.PI / 2, 0, 0]} scale={0.187}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.M_MetalRuler_SF} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pendulum.gltf')
