/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pipe.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pipe.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Цилиндр_пушки.geometry} material={materials['Material.011']} position={[2.87, 19.533, 6.664]} rotation={[0, 0, -Math.PI / 2]} scale={1.619} />
    </group>
  )
}

useGLTF.preload('/Pipe.gltf')
