/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Plata.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Plata.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.365, 19.436, 5.715]} scale={[0.683, 0.331, 0.008]}>
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Plata.gltf')
