/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 RegulatorBase2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RegulatorBase2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Коробка_напряжения.geometry} material={materials.Plastic} position={[-14.893, 17.602, 4.9]} rotation={[0, -1.571, 0]} scale={[1, 0.32, 1]} />
    </group>
  )
}

useGLTF.preload('/RegulatorBase2.gltf')
