/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 RegulatorBase.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RegulatorBase.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Коробка_напряжения.geometry} material={nodes.Коробка_напряжения.material} position={[-14.893, 17.602, 4.9]} rotation={[0, -1.571, 0]} scale={[1, 0.32, 1]} />
    </group>
  )
}

useGLTF.preload('/RegulatorBase.gltf')
