/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 roundBullet.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/roundBullet.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Iron with Splashed Paint']} position={[-1.192, 17.491, 5.667]} scale={0.232} />
    </group>
  )
}

useGLTF.preload('/roundBullet.gltf')
