/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 stol_4.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/stol_4.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.iron_table.geometry} material={materials['Artisan oak, kronospan, wood.']} position={[15.501, 8.057, 9.781]} scale={[0.523, 8.698, 0.523]} />
    </group>
  )
}

useGLTF.preload('/stol_4.gltf')
