/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Weight.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Weight.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.012']} position={[11.153, 19.51, 6.69]} rotation={[0, 0, -Math.PI / 2]} scale={[0.284, 0.639, 0.284]} />
    </group>
  )
}

useGLTF.preload('/Weight.gltf')
