/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 window.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/window.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-17.536, 25.827, 85.828]} rotation={[Math.PI, 0, Math.PI]} scale={24.757}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.iron} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['sheet metal']} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.hlinik} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials.guma} />
      </group>
    </group>
  )
}

useGLTF.preload('/window.gltf')
