/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WireClemmRegulator.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WireClemmRegulator.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wiring_1.geometry} material={materials['Material.015']} position={[-15.566, 17.486, 3.501]} rotation={[Math.PI / 2, 0, -3.142]} scale={[0.127, 0.664, 0.127]} />
    </group>
  )
}

useGLTF.preload('/WireClemmRegulator.gltf')
