/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WolmeterGlass.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WolmeterGlass.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-12.899, 18.318, 9.178]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.020']} />
      </group>
    </group>
  )
}

useGLTF.preload('/WolmeterGlass.gltf')
